version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: catcosy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catcosy
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - catcosy-network

  # Library Service
  library:
    build:
      context: .
      dockerfile: library/Dockerfile
    # image: vietquoc2408/catcosy-library:1.0.0
    container_name: catcosy-library
    restart: always
    ports:
     - "8080:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catcosy?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - catcosy-network

  # Admin Service
  admin:
    build:
      context: .
      dockerfile: admin/Dockerfile
    # image: vietquoc2408/catcosy-admin:1.0.0
    container_name: catcosy-admin
    restart: always
    ports:
      - "8081:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catcosy?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: default
      
    depends_on:
      mysql:
        condition: service_healthy
      library:
        condition: service_started
    networks:
      - catcosy-network

  # Customer Service
  customer:
    build:
      context: .
      dockerfile: customer/Dockerfile
    # image: vietquoc2408/catcosy-customer:1.0.0
    container_name: catcosy-customer
    restart: always
    ports:
      - "8082:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catcosy?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: default
    
    depends_on:
      mysql:
        condition: service_healthy
      library:
        condition: service_started
    networks:
      - catcosy-network

networks:
  catcosy-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local