version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: catcosy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catcosy
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - catcosy-network
    command: --default-authentication-plugin=mysql_native_password

  library:
#    build:
#      context: .
#      dockerfile: library/Dockerfile
    image: vietquoc2408/catcosy-library:1.0.0
    container_name: catcosy-library
    restart: always
    ports:
      - "8080:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catcosy?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: default
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - catcosy-network

  admin:
#    build:
#      context: .
#      dockerfile: admin/Dockerfile
    image: vietquoc2408/catcosy-admin:1.0.0
    container_name: catcosy-admin
    restart: always
    ports:
      - "8081:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catcosy?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: default
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysql:
        condition: service_healthy
      library:
        condition: service_started
    networks:
      - catcosy-network

  customer:
#    build:
#      context: .
#      dockerfile: customer/Dockerfile
    image: vietquoc2408/catcosy-customer:1.0.0
    container_name: catcosy-customer
    restart: always
    ports:
      - "8082:8086"
    env_file:
      - ./customer/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catcosy?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: default
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysql:
        condition: service_healthy
      library:
        condition: service_started
    networks:
      - catcosy-network

networks:
  catcosy-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local